// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEOVqgrWVDnOhGMTJhaoHh6tRZUIyq3A',
    appId: '1:335856038398:web:eb0376f97cfb48147010af',
    messagingSenderId: '335856038398',
    projectId: 'assignmnet-f9870',
    authDomain: 'assignmnet-f9870.firebaseapp.com',
    storageBucket: 'assignmnet-f9870.appspot.com',
    measurementId: 'G-42L23QMNXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPf6QVhMNFvB1Ygl8gwdBXuRzNXmEkLBI',
    appId: '1:335856038398:android:a3c08c5a3987eace7010af',
    messagingSenderId: '335856038398',
    projectId: 'assignmnet-f9870',
    storageBucket: 'assignmnet-f9870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArn5aOq2gfkpYibSdWjjKRxDeEVN-t9go',
    appId: '1:335856038398:ios:f93a5771c8237a567010af',
    messagingSenderId: '335856038398',
    projectId: 'assignmnet-f9870',
    storageBucket: 'assignmnet-f9870.appspot.com',
    iosClientId: '335856038398-h2r16s6272mkg1mk4r6lki5d9crp1vos.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArn5aOq2gfkpYibSdWjjKRxDeEVN-t9go',
    appId: '1:335856038398:ios:f93a5771c8237a567010af',
    messagingSenderId: '335856038398',
    projectId: 'assignmnet-f9870',
    storageBucket: 'assignmnet-f9870.appspot.com',
    iosClientId: '335856038398-h2r16s6272mkg1mk4r6lki5d9crp1vos.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
